-- Every authored squad in powerhouse. Groups follow the route, not package enumeration order.
return {
    catwalk_entry = {
        "CATWALK_ENTRY_RANGED_A_SQUAD", "CATWALK_ENTRY_RANGED_B_SQUAD",
        "CATWALK_ENTRY_SUPPORT_A_SQUAD", "CATWALK_ENTRY_SUPPORT_B_SQUAD",
        "CATWALK_ENTRY_SUPPORT_C_SQUAD",
    },
    catwalk_mid = {
        "CATWALK_MID_SUPPORT_A_SQUAD", "CATWALK_MID_SUPPORT_B_SQUAD",
        "CATWALK_MID_SUPPORT_C_SQUAD", "CATWALK_BONUS_SUPPORT_A_SQUAD",
    },
    pipe = {"PIPE_CROSSING_SUPPORT_A_SQUAD", "PIPE_CROSSING_SUPPORT_B_SQUAD"},
    mercury = {
        "LANDING_MERCURY_ANCHOR_SQUAD",
        "LANDING_MERCURY_SUPPORT_A_SQUAD", "LANDING_MERCURY_SUPPORT_B_SQUAD",
        "LANDING_MERCURY_SUPPORT_C_SQUAD", "LANDING_MERCURY_RANGED_A_SQUAD",
        "LANDING_MERCURY_RANGED_B_SQUAD",
        -- Both authored vignette groups occupy the Mercury end of the bridge.
        "BRIDGE_VIGNETTE_SUPPORT_A_SQUAD", "BRIDGE_VIGNETTE_SUPPORT_B_SQUAD",
    },
    mercury_bonus = {
        "LANDING_MERCURY_BONUS_ANCHOR_A_SQUAD", "LANDING_MERCURY_BONUS_SUPPORT_A_SQUAD",
        "LANDING_MERCURY_BONUS_SUPPORT_B_SQUAD", "LANDING_MERCURY_BONUS_SUPPORT_C_SQUAD",
        "LANDING_MERCURY_BONUS_SUPPORT_D_SQUAD",
    },
    bridge = {
        "BRIDGE_CROSSING_SUPPORT_A_SQUAD", "BRIDGE_CROSSING_SUPPORT_B_SQUAD",
        "BRIDGE_CROSSING_DEFENSE_A_SQUAD", "BRIDGE_CROSSING_DEFENSE_B_SQUAD",
        "BRIDGE_CROSSING_RANGED_A_SQUAD",
    },
    dropships = {
        "BRIDGE_CROSSING_DROPSHIP_A_SQUAD", "BRIDGE_CROSSING_DROPSHIP_B_SQUAD",
        "BRIDGE_CROSSING_DROPSHIP_C_SQUAD", "BRIDGE_CROSSING_DROPSHIP_D_SQUAD",
    },
    passengers = {
        "BRIDGE_CROSSING_DROPSHIP_A_SUPPORT_A_SQUAD",
        "BRIDGE_CROSSING_DROPSHIP_A_SUPPORT_B_SQUAD",
        "BRIDGE_CROSSING_DROPSHIP_A_MELEE_A_SQUAD",
        "BRIDGE_CROSSING_DROPSHIP_A_MELEE_B_SQUAD",
    },
    sun = {"LANDING_SUN_SUPPORT_A_SQUAD", "LANDING_SUN_SUPPORT_B_SQUAD"},
    helipad = {
        "HELIPAD_SUN_ANCHOR_A_SQUAD", "HELIPAD_SUN_SUPPORT_A_SQUAD", "HELIPAD_SUN_SUPPORT_B_SQUAD",
    },
}
